### ISSUE TITLE
Chunky is only trimming region files

### ISSUE THREAD

**Issue by JHarris12345** [pop4959/ChunkyBorder#24]
I am on the latest versions and MC 1.16.5. There is an issue where trimming the world doesnt trim any chunks, it only trims region files. So it trims from the border of the region file and not the worldborder. I.e If I set my border to 100 and try to trim, it wont start trimming until 512 blocks out

**Comment by pop4959** [comment]
Are you sure you aren't too close to spawn, or re-generating the chunks while online? These are common problems for really small regions and near the border. The spawn chunks can't be deleted without disabling the spawn region since they will just be re-saved on shutdown, or re-created on startup.

By the way, this is the ChunkyBorder repository, for Chunky you should report issues [here](https://github.com/pop4959/Chunky) instead. Though for this I'm fairly certain this is just a usage quirk, so if you still have trouble I would recommend joining the [Discord server](https://discord.gg/ZwVJukcNQG) in the #chunky channel and I may be able to help you out.

**Comment by JHarris12345** [comment]
How would I do the regen without being online or near spawn if the radius is near spawn?

**Comment by pop4959** [comment]
You'd want to take a look at Paper's [`keep-spawn-loaded`](https://paper.readthedocs.io/en/latest/server/configuration.html#keep-spawn-loaded) configuration option and trim from console, or use an external tool like mcaselector to delete them while the server isn't running.

If your goal is to delete the whole world, however, you're probably much better off just going into your world's region folder and simply deleting everything in there (along with the entities and POI's to be extra thorough). Again, you'd want to do this with the server offline.

In all cases you can expect chunks loaded by the spawn region or players to re-generate the chunks again within view distance.

**Comment by JHarris12345** [comment]
Keep spawn loaded is false and I did it from console and it still did not work. I am not looking to delete the world, just trim it fom about 287 blocks out

**Comment by pop4959** [comment]
Okay, let's take step back. I still feel like most likely there is just some misunderstanding about how trim works.

> trimming the world doesnt trim any chunks, it only trims region files

How are you determining this? The chunks are stored within region files, so the only files that are fully deleted are the ones where no chunks are inside the selection.

> So it trims from the border of the region file and not the worldborder

> If I set my border to 100 and try to trim, it wont start trimming until 512 blocks out

Again, how was this determined? Is something still there that wasn't trimmed?

If you're still having problems, it might be worth just sending me your world/setup and the commands you are trying to use to trim, and I can confirm whether or not it's working for myself. Sounds like it's a really small world so I don't imagine that would be much of a problem.
