### ISSUE TITLE
Feature request: Trim Command

### ISSUE THREAD

**Issue by TheoRetisch1** [pop4959/ChunkyBorder#3]
It would be fantastic if you could add the trim command ambivalent to the worldborder trim command. The command is the opposite of the fill command and ensures that chunks outside the set worldborder are removed. The Trim Command was always a useful companion and I would be happy to see him again.

commands: 
```
chunkyborder trim 
chunkyborder trim pause 
chunkyborder trim stop
```

**Comment by pop4959** [comment]
Since ChunkyBorder is designed only to manage player borders, this command would be better suited to be included in Chunky instead since it is also responsible for generation.

There is already an issue open at https://github.com/pop4959/Chunky/issues/20 for this. Feel free to leave a thumbs up on that instead, and leave your comments. 😄 

OFF-TOPIC: How are you liking ChunkyBorder so far (if you are using it)? I haven't gotten much feedback from people yet so I'm thinking it is probably working well, but I'm curious to hear what your thoughts might be.
