### ISSUE TITLE
(Suggestion) Fabric support

### ISSUE THREAD

**Issue by mgardner67** [pop4959/ChunkyBorder#32]
Hello! I've been loving the Chunky mod so far—thanks for keeping it updated and working across mod loaders.

Would it be possible to bring this plugin to Fabric, or integrate its functionality into the main Chunky mod?

**Comment by pop4959** [comment]
As it turns out I have recently started investigating this as a possibility. In some of the most recent commits on this project I've started moving things over to be more platform independent. There is still a lot of work to be done, so I can't promise anything specific, but if everything goes smoothly it might happen.

It will most likely still be a separate add-on instead of built straight into Chunky.

**Comment by pop4959** [comment]
Added some initial support in the latest build. Feedback welcome! There will probably be a few more changes to it before the next release.
