### ISSUE TITLE
(Suggestion) Visual particles for borders

### ISSUE THREAD

**Issue by Kapitowa** [pop4959/ChunkyBorder#37]
Add visual particles for circle border

**Comment by pop4959** [comment]
This is something that I'd like to explore eventually, but has not been high priority.

For now, [Selection Visualizer](https://www.spigotmc.org/resources/selection-visualizer.22631/) exists (and yes, I know it's paid -- don't know of any free alternatives right now).

**Comment by Kapitowa** [comment]
I bought this plugin and have this error on startup
https://pastebin.com/rmYCSZ9p

**Comment by Kapitowa** [comment]
https://haste.olziedev.com/etihinibad.md
I have this error on startup

**Comment by pop4959** [comment]
> https://haste.olziedev.com/etihinibad.md I have this error on startup

It looks like Selection Visualizer is not properly integrating with the latest version of ChunkyBorder. I've gone ahead and reported this to the author so they can look into fixing that. For the time being, if you wish to use the integration the easiest way for now would be to revert to [Chunky 1.2.86](https://www.spigotmc.org/resources/chunky.81534/history) + [ChunkyBorder 1.0.38](https://www.spigotmc.org/resources/chunkyborder.84278/history).

**Comment by pop4959** [comment]
Initial implementation completed in [0423589](https://github.com/pop4959/ChunkyBorder/commit/04235892ac022f3f7c6becba25c7d53f6c27c891).

ChunkyBorder now has a particle visualizer, as well as a real world border renderer (however this requires installation client-side).

The client-side renderer takes priority -- so if the server has the particle visualizer enabled, it will not display to users with the mod, only users without the mod (who otherwise wouldn't be able to see the border).

I have been working on this for a while, so I hope everyone enjoys the new functionality!
