### ISSUE TITLE
[Request] Nether portal behaviour the same as vanilla

### ISSUE THREAD

**Issue by kencinder** [pop4959/ChunkyBorder#40]
As per discussion in the Bluemap discord, it would be nice if ChunkyBorder could redirect nether portal generation in the same way the vanilla worldborder does.

**Comment by lokka30** [comment]
What currently happens with nether portals in Chunky?

E.g. if nether and overworld both have a radius of 4k blocks, what happens if I build a portal in the Nether at the border? 
Without ChunkyBorder, the portal in the overworld should generate very far from where the border finishes. Unsure what CB does when the overworld border is too small

**Comment by lokka30** [comment]
Thank you very much for the reply pop - understood.

I'll contribute wherever I can, and I've subscribed to this thread. I wish I could help with a PR, though I don't want to produce a pile of spaghetti since I have no clue how to use the Bukkit API for this purpose.

Give me a ping whenever you like 👍🏻

**Comment by pop4959** [comment]
This doesn't appear to be possible via the API right now so I will unfortunately be closing as "wontfix". 😦

If it becomes feasible in the future I'll definitely take a look at this again though.
