### ISSUE TITLE
Crash when teleporting from Nether->Overworld outside WordBorder

### ISSUE THREAD

**Issue by Farsinuce** [pop4959/ChunkyBorder#42]
**Error 1:**
Regarding a vanilla MC WorldBorder, set to [small-size].
1. Go to Nether
2. Go through new portal far away, back to overworld
3. You are now outside the vanilla worldborder = Client loads forever.
Log: [https://pastebin.com/6epS2Qwt](https://pastebin.com/6epS2Qwt)

**Error 2:**
Regarding a Chunky Border, set to [small-size] (but large vanilla worldborder)
1. Go to Nether
2. Go through new portal far away, back to overworld
3. You are still inside the vanilla worldborder, but outside Chunky's border
Log: [https://pastecode.io/s/u1o2xuc8](https://pastecode.io/s/u1o2xuc8)

**Versions:**
Minecraft 1.19
Fabric Loader 14.8, API 0.56.0
Chunky 1.2.202
ChunkyBorder 1.0.70

**Comment by Sinuce** [comment]
Thank you for looking into this and spending your time on it.

Sorry, no, I do not have any other specific way to describe how to reproduce the error. My server crashed consistently on me, when I went through a portal to the overworld, that lead to coordinates outside of the set world border.

I have removed Chunky Border, and now everything works fine. Instead of using Chunky Border, I just manually increase the vanilla world border from time to time, and I have set the damage to 0, which sort of takes care of what I initially wanted to use Chunky Border for.

Thank you for your time.
Let's close this issue.
