### ISSUE TITLE
Bug with teleporting outside border

### ISSUE THREAD

**Issue by moonies44** [pop4959/ChunkyBorder#44]
Issue i have found - scenario.

1. a player has permission to bypass the chunky border.
2. a second player does not have permission to pass the chunky border
3. If a teleport is used (from any plugin such as essentials tpa, or tpall) to a player that doesn't have border bypass, the player who does not have permission to border byoass to the person whgo does will then be teleported on top of the nether roof.
hope this helps :3
1.17.1 paper.

**Comment by pop4959** [comment]
Thanks for the report!

I think the issue here is mostly specific to the nether, as it's intended for teleport redirection to push you back into the border on the highest block currently. However with the roof that is quite a problem!

I will have to revisit the logic there and see if any improvements can be made.

**Comment by pop4959** [comment]
@moonies44 I've changed the behavior in the latest build of Chunky and ChunkyBorder.

Now the redirected teleport elevation is the highest block *below* the maximum elevation in the world.

As always, if no valid location is found the player will teleport to the world spawn instead.
