### ISSUE TITLE
Border does not prevent tp outside it

### ISSUE THREAD

**Issue by SlimeDog** [pop4959/ChunkyBorder#5]
Spigot 1.16.3
LuckPerms 5.2.16
Chunky 1.1.20
ChunkyBorder 1.0.2

plugins/ChunkyBorder/borders.json
```
{"world":{"world":"world_luckyblock","centerX":0,"centerZ":0,"radiusX":100,"radiusZ":100,"shape":"square"}}
```
Player SlimeDog is in LuckPerms group `admin`.
```
>perms group admin permission checkinherits chunkyborder.bypass.move
[17:26:03] [pool-13-thread-1/INFO]: [LP] chunkyborder.bypass.move has permission false set to admin in context global. (inherited from default)
>perms group admin permission checkinherits chunkyborder.bypass.place
[17:26:08] [pool-13-thread-1/INFO]: [LP] chunkyborder.bypass.place has permission false set to admin in context global. (inherited from default)
```
Server stopped and restarted. Player SlimeDog connected in `world_luckyblock`.
```
tp SlimeDog -111 ~ -111
```
succeeds in placing player outside border.

**Comment by pop4959** [comment]
I'm not able to replicate this: https://i.pop4959.xyz/aeffcf29-9eb2-4651-820d-f3382e9351f6.gif

Appears to be working fine using latest Spigot 1.16.3, LuckPerms 5.1.86, Chunky 1.1.20, ChunkBorder 1.0.2. Just to clarify, do you have any other plugins installed, or only those four?

**Comment by SlimeDog** [comment]
> Appears to be working fine using latest Spigot 1.16.3, LuckPerms 5.1.86, Chunky 1.1.20, ChunkBorder 1.0.2. Just to clarify, do you have any other plugins installed, or only those four?

Only 150 other plugins. The servers are used to test plugins. I will start an isolation cycle.

**Comment by pop4959** [comment]
Ah OK good to know. Very likely some plugin then. ChunkyBorder currently uses PlayerTeleportEvent listening at the lowest priority, which is the same event and priority as other border plugins like WorldBorder (and done intentionally that way to avoid breakage with other plugins expecting that). If you find a plugin that's causing issues, let me know, since I'd be curious to figure out why it isn't compatible.

Also, might be smart to start by removing all plugins except Chunky/Border just in case you are able to replicate your issue without anything else installed. That should be faster than cycling right from the get-go, and if the problem persists, you know it's a plugin conflict.

**Comment by SlimeDog** [comment]
I don't doubt that it's a conflict. My process is to start with a minimum subset that includes the plugin(s) of interest -- in this case, Chunky and ChunkyBorder -- and proceed from there, based on the results. I've done it many times. You might be surprised how many plugins engender conflicts (or maybe not).

**Comment by SlimeDog** [comment]
Just out of curiosity, what was your plugin list? Just the three? In that case, you were in world `world`. As noted earlier, I was in `world_luckyblock`, managed by `Multiverse-Core` and siblings.

**Comment by SlimeDog** [comment]
And then again, sometimes it's just PEBKAC. Mea culpa.

**Comment by pop4959** [comment]
No problem. If you found anything else that you think needs attention, definitely feel free to make another issue. I can't promise I'll do everything, but I'm definitely looking to make gradual improvements over time with Chunky and this plugin. Trying to take the time to make sure I do things right, and take some steps forward, and hopefully not too many backward. A lot of this stuff just takes a lot of testing to make sure it's stable... which is why I really appreciate people like you who help out, since not that many people do.
