### ISSUE TITLE
Running /bluemap reload removed the border

### ISSUE THREAD

**Issue by ArmonicPvP** [pop4959/ChunkyBorder#52]
When doing /bluemap reload and reloading the web page, the border disappears

**Comment by pop4959** [comment]
Thanks for the report! Should be fixed in https://github.com/pop4959/ChunkyBorder/commit/c2287845e79f07c4ef2e113e7582f0e738593865.

You can download the build from [Github Actions](https://github.com/pop4959/ChunkyBorder/actions) or [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/ChunkyBorder/).
