### ISSUE TITLE
NeoForge Support

### ISSUE THREAD

**Issue by kasperbjerby** [pop4959/ChunkyBorder#58]
Pretty please?

**Comment by pop4959** [comment]
Maybe about time to start thinking about. Chunky on Forge has gotten a bit more popular recently, so maybe this makes sense now. I'll think about it a bit, although I may not have time to port back to old versions.

**Comment by pop4959** [comment]
I was looking into this again recently. With NeoForge introduced into the mix, I will probably not be adding support for Forge, but rather NeoForge exclusively. It looks like this should be much easier to port directly based on the changes introduced in NeoForge vs old Forge. Updating this issue to indicate the change in plans here.

Still might be a bit before I get around to this, but likely will happen sooner rather than later at this point.

**Comment by pop4959** [comment]
Implemented in ae2c412e36be1a2d13c2c2c81e7a66e6b8a2575d. There are some bugs in Forge which make it such that the client border renderer does not function currently, however the particle renderer works fine, as well as teleporting the player into the border. Likely will fix these in a future version as changes appear to be on the horizon on Forge's side.

NeoForge also isn't implemented yet, as I would like to have Forge stable (or abandon it) before I add yet another version. If it was working properly I was going to support both though.

I hope you enjoy!
