### ISSUE TITLE
Support for Minecraft version 1.20.1 (Forge)

### ISSUE THREAD

**Issue by barthogenes** [pop4959/ChunkyBorder#69]
Hello, is it possible to support version 1.20.1?
I am setting up a server for All the Mods 9 - No Frills, which runs on 1.20.1, and I would like to use this mod's round-world border shape feature.
I get the following error when starting the server using ChunkyBorder-1.1.59:
[main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'minecraft', Requested by: 'chunkyborder', Expected range: '[1.20.2,1.21)', Actual version: '1.20.1'

**Comment by pop4959** [comment]
Unfortunately no plans, there are breaking changes between 1.20.1 and 1.20.2 so it requires more than just labelling it as supported, and I generally have no interest in backporting (even if it is a relatively minor change).

I understand that there are mod packs on older versions where it might be helpful if it was supported, but I have to draw a line somewhere for my own sake. I appreciate your understanding, and I hope you're able to use it with a newer mod pack in the future.

Alternatively, the mod is open source and you are welcome to fork and backport it yourself for your own personal use.

**Comment by pop4959** [comment]
Just because I was curious now, I went back to see if I could even add 1.20.1 support - I was able to on Fabric, but apparently for Forge, 1.20.1 is missing an event that the mod relies upon that were quite literally added in 1.20.2. I forgot about this.

So basically, for anyone looking to backport this, it is probably more effort than it is worth. This mod didn't support Forge for a very long time, and the main reason was all of these issues preventing me from porting it properly.

Still quite a few issues with Forge anyway, the current mod is basically a proof of concept. The networking is a huge mess right now (on Forge's end, not the fault of the mod), and I'm hoping that this gets resolved by 1.21 and we can have full parity with the Fabric version.

**Comment by Romaq** [comment]
Thank you for your response on this issue. I'm watching ATM 9, Gravitas2 in particular. Much of the 1.20.1 centers on the Create Mod. Create Mod *is* being updated to newer versions of Minecraft, so my plan is to enjoy what I have and wait for the Create (and everybody else) updates. I'm expecting to see Gravitas2 getting up there also.

I can't wait! But yeah, I'll wait. :)
